# Vectors

In [4]:
import numpy as np

lst = [10,20,30,40,50]

vctr = np.array(lst)

print("vector created from a list:")
print(vctr)

vector created from a list:
[10 20 30 40 50]


In [7]:
import numpy as np

lst1 = [10,20,30,40,50]
lst2 = [1,2,3,4,5]


vctr1 = np.array(lst1)

vctr2 = np.array(lst2)

print(vctr1)
print(vctr2)
vctr_add = vctr1+vctr2
print("Addition of two vector: ",vctr_add)

[10 20 30 40 50]
[1 2 3 4 5]
Addition of two vector:  [11 22 33 44 55]


In [9]:
import numpy as np

#define vector 
x = np.array ([3, 6, 6, 4, 8, 12, 13])

#calculate magnitude of vector
np.linalg.norm(x)

21.77154105707724

In [10]:
#define vector 
x = np.array([3, 6, 6, 4, 8, 12, 13])
#calculate magnitude of vector
np.sqrt(x.dot(x))
np.sqrt(np.dot(x,x))

21.77154105707724