In [2]:
import numpy as np
a=np.matrix('1 2 3 ;4 5 6;7 8 9')
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
print(a.shape)

(3, 3)


In [13]:
import numpy as np
b=np.array([[3,0,2],[7,5,9],[1,4,5]])
print(a+b)


[[ 4  2  5]
 [11 10 15]
 [ 8 12 14]]


In [14]:
print(a*2)


[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [15]:
print(a-b)


[[-2  2  1]
 [-3  0 -3]
 [ 6  4  4]]


In [16]:
print(a*b)


[[ 3  0  6]
 [28 25 54]
 [ 7 32 45]]


In [17]:
c=np.matrix.transpose(a)
print(c)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
import numpy as np
import sympy as su
from sympy import*


In [2]:
pip install itertools

Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement itertools (from versions: none)
ERROR: No matching distribution found for itertools
Note: you may need to restart the kernel to use updated packages.


In [1]:
from itertools import*
a=permutations([1,2,3,4,5])
count=0
for i in a:
    print(i)
    count +=1

print(count)

(1, 2, 3, 4, 5)
(1, 2, 3, 5, 4)
(1, 2, 4, 3, 5)
(1, 2, 4, 5, 3)
(1, 2, 5, 3, 4)
(1, 2, 5, 4, 3)
(1, 3, 2, 4, 5)
(1, 3, 2, 5, 4)
(1, 3, 4, 2, 5)
(1, 3, 4, 5, 2)
(1, 3, 5, 2, 4)
(1, 3, 5, 4, 2)
(1, 4, 2, 3, 5)
(1, 4, 2, 5, 3)
(1, 4, 3, 2, 5)
(1, 4, 3, 5, 2)
(1, 4, 5, 2, 3)
(1, 4, 5, 3, 2)
(1, 5, 2, 3, 4)
(1, 5, 2, 4, 3)
(1, 5, 3, 2, 4)
(1, 5, 3, 4, 2)
(1, 5, 4, 2, 3)
(1, 5, 4, 3, 2)
(2, 1, 3, 4, 5)
(2, 1, 3, 5, 4)
(2, 1, 4, 3, 5)
(2, 1, 4, 5, 3)
(2, 1, 5, 3, 4)
(2, 1, 5, 4, 3)
(2, 3, 1, 4, 5)
(2, 3, 1, 5, 4)
(2, 3, 4, 1, 5)
(2, 3, 4, 5, 1)
(2, 3, 5, 1, 4)
(2, 3, 5, 4, 1)
(2, 4, 1, 3, 5)
(2, 4, 1, 5, 3)
(2, 4, 3, 1, 5)
(2, 4, 3, 5, 1)
(2, 4, 5, 1, 3)
(2, 4, 5, 3, 1)
(2, 5, 1, 3, 4)
(2, 5, 1, 4, 3)
(2, 5, 3, 1, 4)
(2, 5, 3, 4, 1)
(2, 5, 4, 1, 3)
(2, 5, 4, 3, 1)
(3, 1, 2, 4, 5)
(3, 1, 2, 5, 4)
(3, 1, 4, 2, 5)
(3, 1, 4, 5, 2)
(3, 1, 5, 2, 4)
(3, 1, 5, 4, 2)
(3, 2, 1, 4, 5)
(3, 2, 1, 5, 4)
(3, 2, 4, 1, 5)
(3, 2, 4, 5, 1)
(3, 2, 5, 1, 4)
(3, 2, 5, 4, 1)
(3, 4, 1, 2, 5)
(3, 4, 1, 5, 2)
(3, 4, 2