In [3]:
import numpy as np

a= np.matrix('1 2 3;4 5 6')
b=np.array([[1,2,3],[4,5,6]])
print(b)
print(a)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [4]:
print(a.shape)

(2, 3)


In [6]:
a=np.matrix('1 1;2 43')
b=np.matrix('1 4;1 32')
print(a+b)

[[ 2  5]
 [ 3 75]]


Scalar multipication

In [7]:
a=np.matrix('2 1;2 2;3 3')
a
print(4*a)


[[ 8  4]
 [ 8  8]
 [12 12]]


Matrix multipication

In [9]:
a=np.matrix('1 2 3;4 5 6')
b=np.matrix('2 4 5;2 45 6;2 1 6')
c=a*b
print(c)

[[ 12  97  35]
 [ 30 247  86]]


Transpose of matrix

In [10]:
a=np.matrix('2 4 6;2 43 56;2 3 54')
b=np.matrix.transpose(a)
print(b)

[[ 2  2  2]
 [ 4 43  3]
 [ 6 56 54]]
