In [4]:
import numpy as np

a= np.matrix('2 3 4;4 5 6')
b=np.array([[1,2,3],[4,5,6]])
print(b)
print(a)

[[1 2 3]
 [4 5 6]]
[[2 3 4]
 [4 5 6]]


In [4]:
print(a.shape)

(2, 3)


In [24]:
a=np.matrix('1 1;2 43')
b=np.matrix('1 4;1 32')
c=a+b
print(c)

[[ 2  5]
 [ 3 75]]


Scalar multipication

In [5]:
a=np.matrix('2 1;2 2;3 3')
a



matrix([[2, 1],
        [2, 2],
        [3, 3]])

Matrix multipication

In [21]:
a=np.matrix('1 2 2;4 5 4')
b=np.matrix('2 4 5;2 45 6;2 1 6')
print(a.shape)
print(b.shape)
c=a*b
print(c)

(2, 3)
(3, 3)
[[ 10  96  29]
 [ 26 245  74]]


Transpose of matrix

In [22]:
a=np.matrix('1 2 3;4 5 6;7 8 9')
b=np.matrix.transpose(a)
print(b)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [10]:
a=np.matrix('1 2 3;4 5 6')
a

matrix([[1, 2, 3],
        [4, 5, 6]])