In [1]:
import numpy as np

In [27]:
a=np.matrix('1 4 3;5 4 1;8 5 4')

b=np.array([[1,2,3],[5,7,6],[5, 9,2]])

c=np.matrix('2 6 3;8 6 4;7 3 1')


Add,sub,mul

In [ ]:
print(a)
print(c)
print(a+c)
print(a*c)
print(a-b)

[[1 4 3]
 [5 4 1]
 [8 5 4]]
[[2 6 3]
 [8 6 4]
 [7 3 1]]
[[ 3 10  6]
 [13 10  5]
 [15  8  5]]
[[55 39 22]
 [49 57 32]
 [84 90 48]]
[[ 0  2  0]
 [ 0 -3 -5]
 [ 3 -4  2]]


Determinant,Invers and Eign

In [29]:
print(np.linalg.det(a))
print(np.linalg.inv(a))
eign_value ,eign_vactor= np.linalg.eig(a)

print("Eign Valus:",eign_value)
print("Eign vactor:", eign_vactor)


-57.999999999999986
[[-0.18965517  0.01724138  0.13793103]
 [ 0.20689655  0.34482759 -0.24137931]
 [ 0.12068966 -0.46551724  0.27586207]]
Eign Valus: [10.81564716 -3.39514033  1.57949317]
Eign vactor: [[-0.41845756 -0.74273269  0.12227941]
 [-0.42476868  0.43312585 -0.5840991 ]
 [-0.80278567  0.510637    0.80241883]]


Slicing

In [12]:
x=a[ : 2 ,  : 2 ]
print(x)

[[1 4]
 [5 4]]


Vactors

Add & Sub

In [19]:
b=np.array([2,4,-2])
c=np.array([2,-6,1])
print(b+c)

[ 4 -2 -1]


magnitude of a vactor

In [20]:
print(np.linalg.norm(b))

4.898979485566356


In [22]:
print(np.sqrt(b.dot(b)))

4.898979485566356


In [24]:
import transformations as tr

In [25]:
a = np.array([1,2,8])
print(tr.unit_vector(a))

[0.12038585 0.24077171 0.96308682]


Solving Two Matrices

In [4]:
z = np.matrix('2 3 1;1 5 5;4 -1 3')
x = np.matrix('5;3;2')
print(np.linalg.solve(z,x))

[[ 1.28571429]
 [ 1.04285714]
 [-0.7       ]]


Permutations And combinations

In [5]:
pip install itertools

Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement itertools (from versions: none)
ERROR: No matching distribution found for itertools
Note: you may need to restart the kernel to use updated packages.


In [9]:
from itertools import*
a = [1,2,3,4,5]
perm_of_a=permutations(a)
count=0
for i in perm_of_a:
    print(i)
    count+=1
print(count)

(1, 2, 3, 4, 5)
(1, 2, 3, 5, 4)
(1, 2, 4, 3, 5)
(1, 2, 4, 5, 3)
(1, 2, 5, 3, 4)
(1, 2, 5, 4, 3)
(1, 3, 2, 4, 5)
(1, 3, 2, 5, 4)
(1, 3, 4, 2, 5)
(1, 3, 4, 5, 2)
(1, 3, 5, 2, 4)
(1, 3, 5, 4, 2)
(1, 4, 2, 3, 5)
(1, 4, 2, 5, 3)
(1, 4, 3, 2, 5)
(1, 4, 3, 5, 2)
(1, 4, 5, 2, 3)
(1, 4, 5, 3, 2)
(1, 5, 2, 3, 4)
(1, 5, 2, 4, 3)
(1, 5, 3, 2, 4)
(1, 5, 3, 4, 2)
(1, 5, 4, 2, 3)
(1, 5, 4, 3, 2)
(2, 1, 3, 4, 5)
(2, 1, 3, 5, 4)
(2, 1, 4, 3, 5)
(2, 1, 4, 5, 3)
(2, 1, 5, 3, 4)
(2, 1, 5, 4, 3)
(2, 3, 1, 4, 5)
(2, 3, 1, 5, 4)
(2, 3, 4, 1, 5)
(2, 3, 4, 5, 1)
(2, 3, 5, 1, 4)
(2, 3, 5, 4, 1)
(2, 4, 1, 3, 5)
(2, 4, 1, 5, 3)
(2, 4, 3, 1, 5)
(2, 4, 3, 5, 1)
(2, 4, 5, 1, 3)
(2, 4, 5, 3, 1)
(2, 5, 1, 3, 4)
(2, 5, 1, 4, 3)
(2, 5, 3, 1, 4)
(2, 5, 3, 4, 1)
(2, 5, 4, 1, 3)
(2, 5, 4, 3, 1)
(3, 1, 2, 4, 5)
(3, 1, 2, 5, 4)
(3, 1, 4, 2, 5)
(3, 1, 4, 5, 2)
(3, 1, 5, 2, 4)
(3, 1, 5, 4, 2)
(3, 2, 1, 4, 5)
(3, 2, 1, 5, 4)
(3, 2, 4, 1, 5)
(3, 2, 4, 5, 1)
(3, 2, 5, 1, 4)
(3, 2, 5, 4, 1)
(3, 4, 1, 2, 5)
(3, 4, 1, 5, 2)
(3, 4, 2

In [13]:
a = [1,2,3,4,5]
Z=permutations(a,3)
count=0
for i in Z:
    print(i)
    count+=1
print(count)

(1, 2, 3)
(1, 2, 4)
(1, 2, 5)
(1, 3, 2)
(1, 3, 4)
(1, 3, 5)
(1, 4, 2)
(1, 4, 3)
(1, 4, 5)
(1, 5, 2)
(1, 5, 3)
(1, 5, 4)
(2, 1, 3)
(2, 1, 4)
(2, 1, 5)
(2, 3, 1)
(2, 3, 4)
(2, 3, 5)
(2, 4, 1)
(2, 4, 3)
(2, 4, 5)
(2, 5, 1)
(2, 5, 3)
(2, 5, 4)
(3, 1, 2)
(3, 1, 4)
(3, 1, 5)
(3, 2, 1)
(3, 2, 4)
(3, 2, 5)
(3, 4, 1)
(3, 4, 2)
(3, 4, 5)
(3, 5, 1)
(3, 5, 2)
(3, 5, 4)
(4, 1, 2)
(4, 1, 3)
(4, 1, 5)
(4, 2, 1)
(4, 2, 3)
(4, 2, 5)
(4, 3, 1)
(4, 3, 2)
(4, 3, 5)
(4, 5, 1)
(4, 5, 2)
(4, 5, 3)
(5, 1, 2)
(5, 1, 3)
(5, 1, 4)
(5, 2, 1)
(5, 2, 3)
(5, 2, 4)
(5, 3, 1)
(5, 3, 2)
(5, 3, 4)
(5, 4, 1)
(5, 4, 2)
(5, 4, 3)
60


In [16]:
a = [1,2,3,4,5]
x = combinations(a, 2)
count=0
for i in x:
    print(i)
    count+=1
print(count)

(1, 2)
(1, 3)
(1, 4)
(1, 5)
(2, 3)
(2, 4)
(2, 5)
(3, 4)
(3, 5)
(4, 5)
10
